### ISSUE TITLE
Unexpected passed variables value through define

### ISSUE THREAD

**Issue by robhrt7** [gruntjs/grunt-contrib-stylus#104]
I'me defining global variables through define:

``` js
define: {
  test: '1px',
  $color: 'red'
}
```

And from this `input.styl`

``` css
.test {
    font-size: test;
    color: $color;
    }
```

I get wrong, quoted properties:

``` css
.test {
  font-size: '1px';
  color: 'red';
}
```

Here's an expected output:

``` css
.test {
  font-size: 1px;
  color: red;
}
```

Same result with lighter Stylus syntax without braces and semicolons.
