### ISSUE TITLE
Compile directory full of .styl files

### ISSUE THREAD

**Issue by metalshark** [gruntjs/grunt-contrib-stylus#60]
Currently I cannot find a way to compile an entire directory of files only individual ones like so:

```
stylus:
    compile:
        files:
            '<%= yeoman.temp %>/styles/main.css': '<%= yeoman.app %>/styles/main.styl'
```

for other grunt projects I use (apologies, still learning grunt) it is possible to achieve this through the cwd/src/dest syntax like so:

```
autoprefixer:
    dist:
        files: [
            expand: true
            cwd: '<%= yeoman.temp %>/styles/'
            src: '**/*.css'
            dest: '<%= yeoman.temp %>/styles/'
        ]
```

Is there an easy way to compile a directory (and nested directories) full of .styl files into individual .css files?
