### ISSUE TITLE
nib not working

### ISSUE THREAD

**Issue by kirkstrobeck** [gruntjs/grunt-contrib-stylus#64]
I use

```
border-radius 4px
```

in my `.styl` but it compiles out to 

```
border-radius: 4px;
```

which clearly isn't using nib. How can I troubleshoot/resolve this? 

```
stylus:
  compile:
    options:
      compress: false
    files:
      "template/css/common.css": ["template/styl/common.styl"]

# grunt stylus:compile
```
- grunt-cli v0.1.11
- grunt v0.4.2 
- grunt-stylus-contrib 1.3.8
