### ISSUE TITLE
urlfunc is not working into dist env

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [gruntjs/grunt-contrib-stylus#81]
Hi,

This is my stylus config:

``` javascript
stylus: {
      dev: {
        options: { compress: false, relative: true, urlfunc: 'url' },
        files: { 'public/stylesheets/app.css': 'src/stylesheets/app.styl' }
      },
      dist: {
        options: { compress: true, relative: true, urlfunc: 'url' },
        files: { 'dist/stylesheets/app.css': 'src/stylesheets/app.styl' }
      }
    }
```

When I use urlfunc to build embedded base64 image, in dev environment works fine, but in dist the style background-image generates: `stylesheets/data:image` instead `data:image` 

This is the css:

``` css
.logo {
    background-image: url('../images/logo.png');
    width: 70px;
    height: 13px;
    margin-left: 3px;
    display: inline-block;
    vertical-align: text-top;
}
```

Both environment the folder images exists.

Does anybody can help me?

Thanks!
